# Definindo as informações das cartas
cartas = [
    {"nome": "King of Wands", "imagem": "srcs/cartas/kingofwands.png", "significado": "Representa liderança, poder criativo e assertividade. O seu dia pode ser influenciado por uma forte presença masculina, fazendo você se sentir confiante, capaz de assumir o controle e expressar suas ideias com entusiasmo. Você pode estar em uma posição de autoridade ou liderança, tendo a oportunidade de exercer influência sobre os outros, mas aja com responsabilidade e integridade, utilizando seu poder de maneira construtiva e benéfica. Apesar dos desafios você saberá lidar de forma eficaz, utilizando sua determinação e força interior."},
    {"nome": "Queen of Wands", "imagem": "srcs/cartas/queenofwands.png", "significado": "Representa energia, entusiasmo e paixão. Você se sentirá inspirado e motivado, podendo enfrentar desafios com coragem. Sua criatividade estará em alta, permitindo expressar-se artisticamente e encontrar soluções inovadoras. A confiança e liderança serão importantes, podendo assumir um papel de autoridade. Lembre-se de tomar decisões com determinação, aproveitando sua força interior. No entanto, tome cuidado para não se tornar dominador ou autoritário, equilibrando sua liderança com empatia e consideração pelos outros. Evite sobrecarregar-se com muitas responsabilidades para evitar o esgotamento."},
    {"nome": "Knight of Wands", "imagem": "srcs/cartas/knightofwands.png", "significado": "Representa energia, ação e aventura. Pode indicar um dia movimentado, cheio de oportunidades para agir e tomar iniciativa. Ele também pode trazer uma mensagem de confiança, autoexpressão e busca por novas experiências. No entanto, é importante equilibrar o entusiasmo com a cautela e evitar a impulsividade. Pode ser um convite para abraçar a aventura e enfrentar os desafios com determinação."},
    {"nome": "Page of Wands", "imagem": "srcs/cartas/pageofwands.png", "significado": "Pode representar mensagens importantes que podem conter insights valiosos, criatividade, paixão e energia juvenil. Sugere receber notícias importantes, expressar-se artisticamente e abraçar novas experiências com entusiasmo. É um convite para agir corajosamente, tomar iniciativas e aproveitar a energia para alcançar resultados positivos."},
    {"nome": "Ace of Wands", "imagem": "srcs/cartas/aceofwands.png", "significado": "Representa energia, ação e aventura. Ele indica um dia movimentado, cheio de oportunidades para agir e tomar iniciativa com motivação e criatividade. Essa carta traz confiança, autoexpressão e busca por novas experiências. Também simboliza paixão, entusiasmo e crescimento. No entanto, é importante equilibrar o entusiasmo com a cautela e evitar a impulsividade. É um convite para abraçar a aventura e enfrentar os desafios com determinação."},
    {"nome": "Two of Wands", "imagem": "srcs/cartas/twoofwands.png", "significado": "Representa energia, ação e aventura. Indica um dia movimentado, cheio de oportunidades para agir e tomar iniciativa. Também traz uma mensagem de confiança, autoexpressão e busca por novas experiências, deixando seu conforto e assumindo novos riscos. É importante equilibrar o entusiasmo com a cautela e evitar a impulsividade. Pode ser um convite para abraçar a aventura e enfrentar os desafios com determinação."},
    {"nome": "Three of Wands", "imagem": "srcs/cartas/threeofwands.png", "significado": "Representa visão, expansão e progresso. Ele pode indicar um dia com visão ampliada e novas oportunidades. Sua energia está direcionada ao progresso em direção aos objetivos, mas é necessário planejamento e preparação. Pode ser um convite para explorar novos territórios e expandir horizontes. No entanto, é importante equilibrar o entusiasmo com a cautela e evitar a impulsividade. É um lembrete para abraçar a aventura e enfrentar os desafios com determinação e confiança."},
    {"nome": "Four of Wands", "imagem": "srcs/cartas/fourofwands.png", "significado": "Indica um dia marcado por eventos felizes, celebrações e conquistas. É um momento de harmonia, estabilidade e realização. Você pode experimentar alegria, satisfação e um ambiente acolhedor ao seu redor. Este arcano também sugere estabilidade emocional e segurança. Valorize as bênçãos da vida e aproveite as relações importantes. Lembre-se de que suas ações e escolhas pessoais também influenciam seu dia e destino."},
    {"nome": "Five of Wands", "imagem": "srcs/cartas/fiveofwands.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
    {"nome": "", "imagem": "srcs/cartas/.png", "significado": ""},
]